# Nixpacks configuration for Railway deployment
# Adds system dependencies required by WeasyPrint

[phases.setup]
# System packages required for WeasyPrint PDF generation
aptPkgs = [
    'pango1.0',
    'libpango-1.0-0',
    'libpangocairo-1.0-0',
    'libpangoft2-1.0-0',
    'gdk-pixbuf-2.0',
    'libgdk-pixbuf2.0-0',
    'libffi-dev',
    'libcairo2',
    'libcairo2-dev',
    'shared-mime-info'
]

[phases.install]
cmds = ['pip install -r requirements.txt']

[start]
cmd = 'uvicorn main:app --host 0.0.0.0 --port $PORT'
